services:
  web:
    image: ubuntu/nginx # imagen de Apache
    container_name: nginx_server # nombre del contenedor
    ports:
      - "80:80" # mapeo de puertos  HTTP
      - "443:443" # mapeo de puertos HTTPS (solo si es necesario)
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf # archivo de configuraci칩n principal (si lo cambias)
      - ./sites-available:/etc/nginx/sites-available # archivos de configuraci칩n de hosts virtuales
      - ./website:/var/www/html/ # directorio de los sitios web
      - ./htpasswd/.htpasswd:/etc/nginx/.htpasswd # archivo de contrase침as
      - ./scripts:/docker-entrypoint.d/ # directorio de scripts
    restart: always # reinicio autom치tico